### ISSUE TITLE
Deploying to all mobile platforms via emulators

### ISSUE THREAD

**Issue by Engil** [LamaUrbain/LamaMobile#11]
We will need to be able to deploy the application to iOS, Android and Windows Phone before next month.
@LouisDuVerdier succeeded on deploying his map widget to Android. Any information about the other platforms? (@Vihess for Windows Phone, maybe?)
Also, is it working with the application itself? (see #4)

**Comment by LouisDuVerdier** [comment]
Deployment OK for physical Android devices but KO for Android emulators.

The emulator itself (Genymotion) crashes at the application startup so I can't try the application on this kind of emulator. The default Android emulator is too slow to be relevant, lagging like hell and taking 20 minutes to initialize itself. I will try again later with the last updates of Genymotion.
