### ISSUE TITLE
Different views depending on whether or not you have the right to edit an itinerary

### ISSUE THREAD

**Issue by Engil** [LamaUrbain/LamaMobile#23]

**Comment by db0company** [comment]
- [ ] If an itinerary doesn't have an owner (ie been created without an authenticated token), anybody can edit it
- [ ] If someone else created an itinerary:
 - Only the authenticated owner can edit it
 - Other users can see the itinerary but in a view that doesn't allow them to edit it

So, there are 2 different kind of views, editable or non-editable:

![screen shot 2015-10-28 at 3 01 36 pm](https://cloud.githubusercontent.com/assets/722281/10804482/ea29b728-7d84-11e5-99e5-cb9dfd91088d.png)
![screen shot 2015-10-28 at 3 02 01 pm](https://cloud.githubusercontent.com/assets/722281/10804483/ea2c6748-7d84-11e5-804a-9843136c5ad8.png)

**Comment by LouisDuVerdier** [comment]
Done.
